### ISSUE TITLE
too_7 parandus

### ISSUE THREAD

**Issue by kuuba** [tiinaaid/tudeng03-kodutood#1]
Ka siin on probleem hulga moodustamisega - hulk saadakse loogeliste sulgude või set() funktsiooni abil. Nurksulgudega teeme me listi ja kuigi in ja not in toimivad ka listil, siis teiste operaatoritega nii lihtsalt ei lähe.

**Comment by kuuba** [comment]
Ma veel lisan, et in ja not in kahe hulga vahel ei toimi, need on element - hulk operaatorid. Hulkade vahel on vaja teisi operaatoreid (k.a. <, >, <= ja >=, mida ma loengus ei maininud).

**Comment by tiinaaid** [comment]
Tahtsin lisada parandatud faili ja järgmise kodutöö aga olen hädas git push käsu kasutamisega. Laadisin failid putty kodutööde kausta kuid ei saa hakkama nende siia laadimisega.

**Comment by kuuba** [comment]
Teed enne ikka nt "git add *" ja git commit -m "Mingi kommentaar selle kohta mida commititakse" ja siis "git push"? Ja kui oled siia midagi vahepeal tekitanud - README-d edinud ntx (või pole päris kindel), siis tee enne ka "git pull". "git status" võib kah midagi huvitavat rääkida.

**Comment by tiinaaid** [comment]
Sain nüüd lisatud aga kodutöö 8 tuli pisut vale kommentaariga.

**Comment by kuuba** [comment]
Git näib kenasti töötavat aga töö 7 hulgaga tehtav tehe küll niimoodi ei tohiks toimiv olla. Tehet seal õieti nagu polegi ju. Ja nii muuseas töö 8 kohta - väga kena algus ja toimivad funktsioonid aga programmi enda ülesehitus mõnevõrra puudulik (lisaks pole ta käivitatav ja moodulina kasutatav). Ootan järgmist versiooni, või muidu võime ka loengu kõrval arutada kah.

**Comment by tiinaaid** [comment]
Muutsin 8ndat kodutööd veidi ja mulle tundub, et nüüd saab seda käivitada.

**Comment by kuuba** [comment]
Ma vaatasin nüüd dragonfish-i kah vahepeal. Seal on küll uus ail tekkinud mida githubi pole pushitud aga ikka on mõned need probleemid alles - et on küll tekkinud vajalikku struktuuri programmile (ja python3 parameetrina käivitub ilmselt kah) aga suur osa on miskipärast välja kommenteeritud ning käsud mis peaks main() funktsiooni all olema, on definitsioonide vahel laiali.

**Comment by kuuba** [comment]
Töö 8 hakkab peaaegu korda saama - esimeses reas ei peaks olema see mis seal on ja kuhi deklaratsioone on kah välja kommenteeritud. Funktsioonide definitsioonid on ka miskipärast main() alla poetatud. Pakuks et kaval oleks kohe töö 9-na üks bioinformaatikaga seotud funktsioon sinna defineerida, siis saan sellega seoses kohe ka töö 8 ära arvestada.

**Comment by kuuba** [comment]
Töö 9 on peaaegu valmis: +x bit on veel faili permissioonidele lisamata. Lisaks veel kommentaariks - fasta on tegelikult päris kehv muutuja nimi ja võib tekitada omajagu segadust.

**Comment by tiinaaid** [comment]
Kui õigesti aru sain, siis on muutus sisse viidud.

**Comment by kuuba** [comment]
Suurepärane. Siis on korras.
